# Generated by Django 5.0.14 on 2026-09-09 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="e.g. 'octo-org/octo-repo'", max_length=255, unique=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('github_installation_token', models.CharField(blank=True, default='', help_text='Short-lived GitHub App / PAT token used for push + PR creation.', max_length=512)),
                ('base_sandbox_image', models.CharField(default='python:3.11-slim', help_text='Base image Nebius Sandboxes should boot for this repo.', max_length=255)),
                ('test_command', models.CharField(default='pytest -q', help_text='Command run inside the sandbox to validate a candidate patch.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_run_id', models.CharField(help_text='The failing GitHub Actions workflow_run.id that triggered this.', max_length=100)),
                ('pull_request_number', models.PositiveIntegerField(blank=True, null=True)),
                ('triggering_commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('primary_log', models.TextField(blank=True, default='', help_text='Raw failing CI log payload.')),
                ('error_summary', models.TextField(blank=True, default='', help_text='Nemotron-generated root-cause summary.')),
                ('resulting_pr_url', models.URLField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SandboxBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.CharField(help_text='Identifier returned by Nebius Token Factory Sandboxes API for this forked sandbox branch.', max_length=255)),
                ('hypothesis_label', models.CharField(help_text="e.g. 'Hypothesis A: Dependency fix'", max_length=50)),
                ('hypothesis_description', models.TextField(blank=True, default='', help_text="Nemotron's reasoning for this fix.")),
                ('patch_diff', models.TextField(blank=True, default='', help_text='Unified diff proposed by Nemotron.')),
                ('test_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('stdout_log', models.TextField(blank=True, default='')),
                ('stderr_log', models.TextField(blank=True, default='')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_used_mb', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agents.analysisrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='winning_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.sandboxbranch'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status'], name='agents_anal_status_59f954_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['repository', 'status'], name='agents_anal_reposit_024351_idx'),
        ),
    ]
